### PR TITLE
Argparse

### PR DESCRIPTION
**Pull request by CJRMoore**
Changed method for parsing arguments from purely positional arguments to using the boost program_options library.  This has the advantage of allowing non-positional arguments (i.e. flags) which is useful for indicating zip files.

Also added a slightly more detailed usage message.

### CODE REVIEW

**Review by rethmecc — COMMENTED** [review]
Why don't we make all arguments non-positional, even the required ones? It would be easier than always trying to remember the position, and would make it more clear what a given command is doing when viewing it in the context of a job submission, such as in the PICOcode processing.

**Comment by CJRMoore** [comment]
That's an easy change to make if we want to do that.  Technically the library requires that all arguments can be used as non-positional arguments (using two dashes) then allowing them to be positional.

**Comment by rethmecc** [comment]
If there's no real downside to doing that, I think we should

**Comment by CJRMoore** [comment]
OK they are now all flagged arguments

**Comment by smfallows** [comment]
This is obviously a worthwhile change, though I'm not clear on whether our goal is to actively discourage unflagged, purely positional arguments or just not to require them. If it's the former, we'll need to update a lot of our documentation to achieve that.

**Comment by rethmecc** [comment]
I think it depends on the code. If it's clear what the software would require (such as the source and destination for the cp command) I think positional arguments is fine. But the fact that AuthoBub requires a run number and a camera mask directory or the fact that the run number argument's position was between the input and output paths isn't all that obvious, so I don't think positional arguments make sense in this case.

**Review by smfallows — APPROVED** [review]
No reason not to do this, whether we abandon some of the legacy argument positions we've had established since time immemorial or not.

**Pull request merged**
